# Generated by Django 5.1 on 2024-09-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0009_alter_userdetail_budgetmonthly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
