# Generated by Django 5.1 on 2024-09-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0011_expense_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='year',
        ),
    ]
